import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { Providers } from "@/shared/ui/providers";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/shared/i18n/routing";
import { setRequestLocale } from "next-intl/server";
import { AppHeader } from "@/features/header";
import { AppFooter } from "@/features/footer";
import { get_categories } from "@/features/categories/api";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

export default async function Layout({ children, params }: Props) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  setRequestLocale(locale);

  const categories = await get_categories(locale);

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={`${inter.className} antialiased`}>
        <Providers>
          <NextIntlClientProvider>
            <AppHeader categories={categories} />
            {children}
            <AppFooter />
          </NextIntlClientProvider>
        </Providers>
      </body>
    </html>
  );
}
